version: '3.9'

services:
  backend:
    build: ./backend
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: "dev-secret-key"
      FILE_ENCRYPTION_KEY: "32byteslongsecretkey32byteslong!"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:8000/api"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securefileshare
    ports:
      - "5432:5432"
